### ISSUE TITLE
Azure Search

### ISSUE THREAD

**Issue by miguelhasse** [VirtoCommerce/vc-module-search#1]
Azure search support source code is commented... is this code to be removed?
When is Azure Search support expected? (https://www.nuget.org/packages/Microsoft.Azure.Search)

**Comment by IgorisB** [comment]
Azure search support is added to Roadmap for 2017, please follow this issue: [Support Azure Search](https://github.com/VirtoCommerce/vc-platform/issues/761). High priority for this feature means it is planned to implement in the next few month. We'll put more precise estimation in next two weeks.
