### ISSUE TITLE
Не работает поиск по нескольким критериям в 3 версии

### ISSUE THREAD

**Issue by vladimir-buravlev** [VirtoCommerce/vc-module-search#15]
Версия Платформы: 3.0.0-rc.4.225
Версия VirtoCommerce.Search: 3.0.0
Проблема:
Ранее (во второй версии) была доступна возможность поиска по нескольким критериям - пользователь мог указать интересующие его критерии в строке поиска "Search keyword..." через пробел, и они применялись как фильтр. Теперь это перестало работать - все критерии кроме первого игнорируются.

В примере ниже мне нужны все пользователи с membertype:Contact и lastname:Pupkin, однако поиск игнорирует вторую часть запроса.
Ожидаемое поведение - в результате должен быть только один элемент.
Наблюдаемое поведение - в результате список, включающий ненужные элементы.
![image](https://user-images.githubusercontent.com/51904345/78768447-39c7d000-798c-11ea-8d9f-3008f717b7c6.png)

**Comment by Aleksandra-Mitricheva** [comment]
Hi @vladimir-buravlev ! 
We checked on the Platform version: 3.29.0-alpha.11630 VirtoCommerce.Search 3.6.0-alpha.498 and  this bug has been fixed.
Please check if this bug is fixed  for you?
