### ISSUE TITLE
Use Virto Commerce without Search Engine module. 

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-search#3]
We use our standalone elastic indices to make queries to and retrieve data and consume it in our storefront and themes project. We don't need any out-of-box module.

We are trying to uninstall the Elasticsearch module which is part of Virto Admin (More -> 
Modules -> Installed -> Elasticsearch module click uninstall here). When we do that and reload the project we get 2 errors. 

I uninstalled CatalogPublishing and SmartCache module. After this the project loads with no errors but , I don’t find any products in my catalog.

Search index tab also has an error.

**As Workaround** we installed Lucene module and Turn off "Use indexed search for catalog" and "Schedule indexing jobs". But now see 500 error when open the product page.

**Expected behaviour:**
Uninstall Search Engine module and work with catalog without it.

**Comment by anivirtoway** [comment]
done
https://github.com/VirtoCommerce/vc-module-search/pull/4
https://github.com/VirtoCommerce/vc-module-core/pull/132

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-core/releases/tag/v2.25.28
