### ISSUE TITLE
FluentAssertions added to production project

### ISSUE THREAD

**Issue by j-mok** [VirtoCommerce/vc-module-search#76]
VirtoCommerce.SearchModule.Core unnecessarily references FluentAssertions NuGet package. FluentAssertions is a typical test project dependency, not production dependency. Unfortunately it transitively "infects" other projects that depend directly or indirectly on [VirtoCommerce.SearchModule.Core package](https://www.nuget.org/packages/VirtoCommerce.SearchModule.Core/3.212.0#dependencies-body-tab)...

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8241 has been created

**Comment by Dan-BV** [comment]
Hi, @j-mok.  
Thank you for your reference. We have created a bug in the current sprint.

**Comment by Dan-BV** [comment]
Hi, @j-mok.
The error has been fixed.

Release https://github.com/VirtoCommerce/vc-module-search/releases/tag/3.213.0

https://github.com/VirtoCommerce/vc-module-search/releases/tag/3.206.5

https://github.com/VirtoCommerce/vc-module-search/releases/tag/3.209.4
